path: D:\cool datasets\OID_people_and_Our_cards\Combined_labelled_dataset
train: train\images
val: valid\images
test: test\images


names:
  0 : human    #you need to have space after and before : otherwise there will be errors
  1 : card